### ISSUE TITLE
Write layer2 block read/write functions for the MRAM chip

### ISSUE THREAD

**Issue by RobertK66** [carstenscharlemann/Climb-Obc-Hardwaretest#12]
IC403 - 1Mbit MRAM

**Comment by andreassinn** [comment]
MR25H10:  "Unlimited write endurance"

**Comment by RobertK66** [comment]
ok, let us challenge this :-D !

**Comment by RobertK66** [comment]
[MR25H10_Datasheet.pdf](https://github.com/carstenscharlemann/Climb-Obc-Hardwaretest/files/4005670/MR25H10_Datasheet.pdf)
