### ISSUE TITLE
Port and refactor the Layer2 EEPROM (and FRAM) functions from pegasus software.

### ISSUE THREAD

**Issue by RobertK66** [carstenscharlemann/Climb-Obc-Hardwaretest#13]
U701-U703 24AA64T-I/MC 64Kb (8K x 8) EEPROM

**Comment by andreassinn** [comment]
maximum 1e6 write cycles

**Comment by RobertK66** [comment]
I will also try to use the Hardware identification block already written by PEG software to Identify the board instance.

**Comment by RobertK66** [comment]
FRAM can use the same block read/write logic here.
IC55 - CY15B128J 128kbit F-RAM
Maximum 1e14 write cycles
