### ISSUE TITLE
Make a layer2 module for read/write to the external Flash 3 (with EEC)

### ISSUE THREAD

**Issue by andreassinn** [carstenscharlemann/Climb-Obc-Hardwaretest#20]

**Comment by RobertK66** [comment]
Can you pls. add a Part Number/Type  for IC7 here? Its not shown in my version of the schematics.

**Comment by andreassinn** [comment]
MT29F1G01ABAFDSF

**Comment by RobertK66** [comment]
This depends on #27

**Comment by RobertK66** [comment]
[DSAAQ0021072.pdf](https://github.com/carstenscharlemann/Climb-Obc-Hardwaretest/files/4005665/DSAAQ0021072.pdf)

**Comment by RobertK66** [comment]
as we are not going tu use this chip in final obc design, I am closing this now.
