### ISSUE TITLE
The OEM13085UL available in FHWN do not work as debugger with MCU 11.0.1

### ISSUE THREAD

**Issue by RobertK66** [carstenscharlemann/Climb-Obc-Hardwaretest#4]
It seems somebody messed around with fimware update. It shows an MBED Drive (comming up if connected) which disconnects-reconnects and then shows a fail.txt file  containing 

` SWD Error`

**Comment by RobertK66** [comment]
It seems somebody messed around with fimware update. It shows an MBED Drive with fail.txt containing  `SWD Error`

**Comment by RobertK66** [comment]
Not sure if all (4?) boards have the same problem. 

@WolfgangTreb: Could you pls. check them all and give some feedback here.

**Comment by RobertK66** [comment]
Other than mine, the boards from WN have Hardware revision D2. So I upgraded the firmware to the same version than mine and it works ok. 

Firmware Update works as following:
- shorten the J4  jumper prior to connecting the board to USB. -> there should appear a drive now in windows explorer with one firmware.bin file. Remove this file by 'delete' and copy the new file to this drive with explorer.
- Reconnect USB and it should work as "CMSIS-DAP V1.0.7" in the MCU Debugger.
This Zip contains the  version I used: 
[FirmwareOEM13085.zip](https://github.com/carstenscharlemann/Climb-Obc-Hardwaretest/files/3775605/FirmwareOEM13085.zip)

**Comment by WolfgangTreb** [comment]
I set the jumper and the explorer opens but without a firmware.bin file. Further, I have no access to copy files onto the board (I tried to copy the new firmware.bin file). Any idea what I am doing wrong?

**Comment by RobertK66** [comment]
How does the drive look. Is it empty? In my case I had this fail.txt on it.
How does it look booting without the jumper?

**Comment by WolfgangTreb** [comment]
No its not empty there are files: ".fseventsd" (dir), ".metadata_never_index", ".Trashes, fail.txt" (with SWD ERROR in it), "mbed.htm"

**Comment by WolfgangTreb** [comment]
I set the jumper next to the USB Interface. Without jumper it is the same. There are 5 smaller jumper occasions, which did not work out neither

**Comment by RobertK66** [comment]
Ah now I see, The 'Jumper J4' here refers to 2 pins which have no 'jumper socket' soldered on. It is only written on the board. (If you hold it USB left side its on the left part of the PCB just right of the 12.000 MHz Quarz (Y4).  You have to contact the 2 pins per hand or solder some wires to it to get it connected.
What you describe above is the 'normal mBed Drive'. I also had on the one board I took but something is wrong with this version -> see content of fail.txt ....
After Flashing the firmware.bin there will be no drive at all when connecting the board.

**Comment by RobertK66** [comment]
Here is a 'official' Document on firmware Updating: 
[LPCXpresso1769_CD_revD_ProductNote.pdf](https://github.com/carstenscharlemann/Climb-Obc-Hardwaretest/files/3790679/LPCXpresso1769_CD_revD_ProductNote.pdf)

Scroll down to rev D1! This also works for D2.

**Comment by WolfgangTreb** [comment]
Hi, It worked out. Just to mention (document): The jumper (J4) has to be replaced again before reconnecting the board and finding it with the MCU debugger

**Comment by WolfgangTreb** [comment]
I will prepare the 3 debugger boards at FHWN in order to distribute them to students if applicable...

**Comment by RobertK66** [comment]
For future references/doing:
You can close an issue with the left button close&comment once everything is resolved. (After closing an issue  all conversation are kept but filtered out from standard view of issue folder). If somebody. disagrees with your closing it can be reopened every time.
