### ISSUE TITLE
Basic Wiki Instructions

### ISSUE THREAD

**Issue by WolfgangTreb** [carstenscharlemann/Climb-Obc-Hardwaretest#8]
I tried to set up a Wiki page with the very basic instructions how to get started with the MCUX SW and work with the debugger boards. 

However there is no "edit" or "new page" option available for my account. Maybe permissions have to be set...

**Comment by RobertK66** [comment]
Ok, i forgot to enter you in the list of colaborators ( = contributers with write access). 
You should now get a invitation message. Pls. check out if it works now.

BTW: You can get credentials for the FHWN account (from Carsten or me next time we meet F2F). Then you can administer this access list - also good for new students ....

**Comment by WolfgangTreb** [comment]
Thanks it works now
